# Generated by Django 6.0.6 on 2026-06-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('language', models.CharField(blank=True, default='', help_text="Language code of the document (e.g., 'ru'). Empty = default", max_length=10, verbose_name='language')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('order', models.IntegerField(default=999, verbose_name='order')),
                ('content_markdown', models.TextField(verbose_name='content')),
                ('section', models.CharField(blank=True, default='', help_text='Section name to display for this page (in same language as document)', max_length=100, verbose_name='section')),
                ('source_path', models.CharField(blank=True, default='', help_text='Absolute path to the source markdown file. Set by update_docs; blank for admin-created pages.', max_length=500, verbose_name='source path')),
                ('anchors', models.JSONField(blank=True, default=list, help_text='Extracted h2/h3 headings. Populated by update_docs.', verbose_name='anchors')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Contents',
                'ordering': ['order'],
                'unique_together': {('slug', 'language')},
            },
        ),
        migrations.CreateModel(
            name='DocSearch',
            fields=[
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Search',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ophix_docs.docpage',),
        ),
        migrations.CreateModel(
            name='DocSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('language', models.CharField(blank=True, default='', max_length=10, verbose_name='language')),
                ('order', models.IntegerField(default=999, verbose_name='order')),
                ('collapsed', models.BooleanField(default=False, verbose_name='collapsed')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['order'],
                'unique_together': {('name', 'language')},
            },
        ),
    ]
