# Generated by Django 5.2.11 on 2026-03-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophix_docs', '0004_alter_docpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='docpage',
            name='language_code',
            field=models.CharField(blank=True, default='', help_text="Language code of the document (e.g., 'ru'). Empty = default", max_length=10),
        ),
        migrations.AddField(
            model_name='docsection',
            name='language',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='docpage',
            name='section',
            field=models.CharField(blank=True, default='', help_text='Section name to display for this page (in same language as document)', max_length=100),
        ),
        migrations.AlterField(
            model_name='docpage',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='docsection',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='docpage',
            unique_together={('slug', 'language_code')},
        ),
        migrations.AlterUniqueTogether(
            name='docsection',
            unique_together={('name', 'language')},
        ),
    ]
