# Generated by Django 5.2.11 on 2026-03-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophix_docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=999)),
                ('collapsed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='docpage',
            options={'ordering': ['section', 'order']},
        ),
        migrations.RenameField(
            model_name='docpage',
            old_name='content_markdown',
            new_name='markdown',
        ),
        migrations.RemoveField(
            model_name='docpage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='docpage',
            name='section',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='docpage',
            name='order',
            field=models.IntegerField(default=999),
        ),
    ]
