# Generated by Django 5.2.11 on 2026-03-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophix_docs', '0002_docsection_alter_docpage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docpage',
            options={'ordering': ['section', 'order'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.RenameField(
            model_name='docpage',
            old_name='markdown',
            new_name='content_markdown',
        ),
        migrations.AddField(
            model_name='docpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='docsection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
