# Generated by Django 5.2.11 on 2026-03-02 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ophix_docs', '0003_alter_docpage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docpage',
            options={'ordering': ['order'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
    ]
