# Generated by Django 5.2.11 on 2026-03-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ophix_docs', '0005_docpage_language_code_docsection_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docpage',
            old_name='language_code',
            new_name='language',
        ),
        migrations.AlterUniqueTogether(
            name='docpage',
            unique_together={('slug', 'language')},
        ),
    ]
