# Generated by Django 6.0.4 on 2026-05-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophix_docs', '0007_docpage_source_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docsection',
            options={'ordering': ['order'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterField(
            model_name='docpage',
            name='content_markdown',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='docpage',
            name='language',
            field=models.CharField(blank=True, default='', help_text="Language code of the document (e.g., 'ru'). Empty = default", max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='docpage',
            name='order',
            field=models.IntegerField(default=999, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='docpage',
            name='section',
            field=models.CharField(blank=True, default='', help_text='Section name to display for this page (in same language as document)', max_length=100, verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='docpage',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='docpage',
            name='source_path',
            field=models.CharField(blank=True, default='', help_text='Absolute path to the source markdown file. Set by ophix_docs_update; blank for admin-created pages.', max_length=500, verbose_name='source path'),
        ),
        migrations.AlterField(
            model_name='docpage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='docpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='docsection',
            name='collapsed',
            field=models.BooleanField(default=False, verbose_name='collapsed'),
        ),
        migrations.AlterField(
            model_name='docsection',
            name='language',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='docsection',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='docsection',
            name='order',
            field=models.IntegerField(default=999, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='docsection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
